server:
  port: 5050

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newmealsys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 2371337